CREATE TABLE USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO_P VARCHAR(50),
    APELLIDO_M VARCHAR(50),
    SEXO BOOLEAN,
    CORREO VARCHAR(80) UNIQUE NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    TIPO_USUARIO TINYINT,
    IMAGEN VARCHAR(255),
    FECHA_NACIMIENTO DATE,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIVACIDAD BOOLEAN
);

CREATE TABLE CATEGORIAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT,
    CREADOR VARCHAR(50)
);

CREATE TABLE PRODUCTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT,
    ID_CATEGORIA INT,
    COTIZAR_VENDER BOOLEAN,
    PRECIO DECIMAL(10,2),
    STOCK INT,
    AUTORIZADO BOOLEAN,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID) ON DELETE SET NULL
);

CREATE TABLE MULTIMEDIA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RUTA_IMAGEN VARCHAR(255),
    RUTA_VIDEO VARCHAR(255),
    ID_PRODUCTO INT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE CASCADE
);

CREATE TABLE VALORACION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    PUNTUACION DECIMAL(3,2),
    ID_PRODUCTO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE CASCADE
);

CREATE TABLE COMENTARIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION TEXT,
    ID_USUARIO INT,
    ID_PRODUCTO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE CASCADE
);

CREATE TABLE CARRITO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO INT,
    ID_USUARIO INT,
    CANTIDAD INT,
    ELIMINADO BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE VENTA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TOTAL DECIMAL(10,2),
    ID_USUARIO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE COMPRA_DETALLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    IMPORTE DECIMAL(10,2),
    ID_VENTA INT,
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE CASCADE
);

CREATE TABLE CHAT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_COMPRADOR INT,
    ID_VENDEDOR INT,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_COMPRADOR) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_VENDEDOR) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE CHAT_DETALLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MENSAJE TEXT,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO INT,
    ID_CHAT INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_CHAT) REFERENCES CHAT(ID) ON DELETE CASCADE
);

CREATE TABLE WISHLIST (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    DESCRIPCION TEXT,
    ID_USUARIO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE WISHLIST_DETALLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ARTICULO INT,
    ID_WISHLIST INT,
    FOREIGN KEY (ID_WISHLIST) REFERENCES WISHLIST(ID) ON DELETE CASCADE
);
